### PR TITLE
Bump stylelint-color-format version

### PR DESCRIPTION
**Pull request by BorisZubchenko**
v1.1.0 allows to provide [custom error message](https://github.com/filipekiss/stylelint-color-format/issues/9#event-3218613366)

### CODE REVIEW

**Comment by sobolevn** [comment]
Thanks a lot!

**Comment by BorisZubchenko** [comment]
Just one question:
How can I update this package in my repository? Is it already published?

**Comment by sobolevn** [comment]
I will publish it tomorrow. Sorry for the delay.

**Comment by sobolevn** [comment]
Done! `@wemake-services/stylelint-config-scss@0.3.0` is out! Thanks for using it.

**Pull request merged**
